services:
  bitcoinii:
    image: kzwo/bitcoin-ii:latest
    container_name: bitcoinii
    restart: unless-stopped

    networks:
      bc2net:
        ipv4_address: 172.30.0.10

    volumes:
      - bc2-data:/data

    ports:
      - "8338:8338"
      - "127.0.0.1:8339:8339"

    command:
      - "-printtoconsole=1"
      - "-server=1"
      - "-rpcport=8337"
      - "-rpcbind=0.0.0.0"
      - "-rpcallowip=172.30.0.0/24"
      - "-txindex=1"

    healthcheck:
      test: ["CMD-SHELL", "bitcoinII-cli -datadir=/data -rpcwait=30 getblockchaininfo >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 120s



  dashboard:
    build: ./dashboard
    container_name: bitcoinii-dashboard
    restart: unless-stopped

    depends_on:
      bitcoinii:
        condition: service_healthy

    networks:
      bc2net:
        ipv4_address: 172.30.0.20

    volumes:
      - bc2-data:/data:ro
    environment:
      RPC_COOKIE: "/data/.cookie"
      RPC_HOST: bitcoinii
      RPC_PORT: "8337"


    ports:
      - "127.0.0.1:3000:3000"


networks:
  bc2net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24

volumes:
  bc2-data:
